package modelo.dto;
// Generated Nov 17, 2016 10:17:35 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="empresa_sw_honney"
)
public class Proyecto  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     private String nombre;
     private Date fechaInicial;
     private Date fechaFinal;
     private Date fechaRealFinal;
     private Set trabajadorProyectos = new HashSet(0);

    public Proyecto() {
    }

	
    public Proyecto(Empresas empresas, String nombre, Date fechaInicial, Date fechaFinal, Date fechaRealFinal) {
        this.empresas = empresas;
        this.nombre = nombre;
        this.fechaInicial = fechaInicial;
        this.fechaFinal = fechaFinal;
        this.fechaRealFinal = fechaRealFinal;
    }
    public Proyecto(Empresas empresas, String nombre, Date fechaInicial, Date fechaFinal, Date fechaRealFinal, Set trabajadorProyectos) {
       this.empresas = empresas;
       this.nombre = nombre;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.fechaRealFinal = fechaRealFinal;
       this.trabajadorProyectos = trabajadorProyectos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPRESAS_ID", nullable=false)
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }

    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_INICIAL", nullable=false, length=10)
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_FINAL", nullable=false, length=10)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_REAL_FINAL", nullable=false, length=10)
    public Date getFechaRealFinal() {
        return this.fechaRealFinal;
    }
    
    public void setFechaRealFinal(Date fechaRealFinal) {
        this.fechaRealFinal = fechaRealFinal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set getTrabajadorProyectos() {
        return this.trabajadorProyectos;
    }
    
    public void setTrabajadorProyectos(Set trabajadorProyectos) {
        this.trabajadorProyectos = trabajadorProyectos;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


