package modelo.dto;
// Generated Nov 17, 2016 10:17:35 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trabajadores generated by hbm2java
 */
@Entity
@Table(name="trabajadores"
    ,catalog="empresa_sw_honney"
)
public class Trabajadores  implements java.io.Serializable {


     private Integer id;
     private String rfc;
     private String nombre;
     private String paterno;
     private String materno;
     private Set trabajadorProyectos = new HashSet(0);

    public Trabajadores() {
    }

	
    public Trabajadores(String rfc, String nombre, String paterno, String materno) {
        this.rfc = rfc;
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
    }
    public Trabajadores(String rfc, String nombre, String paterno, String materno, Set trabajadorProyectos) {
       this.rfc = rfc;
       this.nombre = nombre;
       this.paterno = paterno;
       this.materno = materno;
       this.trabajadorProyectos = trabajadorProyectos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="RFC", nullable=false, length=45)
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    
    @Column(name="NOMBRE", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="PATERNO", nullable=false, length=45)
    public String getPaterno() {
        return this.paterno;
    }
    
    public void setPaterno(String paterno) {
        this.paterno = paterno;
    }

    
    @Column(name="MATERNO", nullable=false, length=45)
    public String getMaterno() {
        return this.materno;
    }
    
    public void setMaterno(String materno) {
        this.materno = materno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="trabajadores")
    public Set getTrabajadorProyectos() {
        return this.trabajadorProyectos;
    }
    
    public void setTrabajadorProyectos(Set trabajadorProyectos) {
        this.trabajadorProyectos = trabajadorProyectos;
    }

    @Override
    public String toString() {
        return nombre;
    }




}


